dataset:
  name: ShapeNet-34
  pc_path: /data1/xp/code/SpareNet/PoinTr/data/ShapeNet55-34/shapenet_pc
  n_points: 8192
  data_path: category_files/ShapeNet-34

model:
  dim_feat: 512
  up_factors: [1, 4, 4]
  num_pc: 256
  num_p0: 512
  bounding: True
  radius: 1.0

train:
  optimizer: {
    type: AdamW,
    kwargs: {
      lr: 0.0005,
      weight_decay: 0.0005
    }}
  scheduler: {
    type: LambdaLR,
    kwargs: {
      decay_step: 21,
      lr_decay: 0.9,
      lowest_decay: 0.02  # min lr = lowest_decay * lr
    }}
  epochs: 200
  gpu: [0]
  batch_size: 32
  num_workers: 8
  loss_func: cd_l2
  seed: 2022
  save_freq: 25
  out_path:
  resume: False
  model_path:

test:
  split: test
  mode: easy
  batch_size: 1
  num_workers: 1
  loss_func: cd_l2
  gpu: [0]
  model_path: /data1/xp/experiments/completion/ShapeNet_34/checkpoints/2022-06-09T13:30:21.219561/ckpt-best.pth